---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: ingress - fields - hosts - paths - path
templates:
  - common.yaml
values:
  - ../_values/ingress_main_default_hosts.yaml
  - ../_values/service_main_default.yaml
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default should pass
    documentSelector:
      path: $[?(@.kind == "Ingress")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.rules[0].http.paths[0].path
          value: "/"

  - it: custom path should pass
    set:
      ingress.main:
        hosts:
          - host: chart-test.local
            paths:
              - path: /test
                service:
                  identifier: main
    documentSelector:
      path: $[?(@.kind == "Ingress")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.rules[0].http.paths[0].path
          value: "/test"

  - it: path with template should pass
    set:
      ingress.main:
        hosts:
          - host: chart-test.local
            paths:
              - path: "/{{ .Release.Name }}.path"
                service:
                  identifier: main
    documentSelector:
      path: $[?(@.kind == "Ingress")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.rules[0].http.paths[0].path
          value: "/RELEASE-NAME.path"
