---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: serviceAccount - fields - secrets
templates:
  - common.yaml
set:
  serviceAccount.main: {}
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: serviceAccount is created without a static token by default
    asserts:
      - documentSelector:
          path: $[?(@.kind == "ServiceAccount")].metadata.name
          value: release-name
        notExists:
          path: secrets
      - not: true
        containsDocument:
          apiVersion: v1
          kind: Secret
          name: release-name-main-sa-token
          any: true

  - it: serviceAccount can be created without a static token
    set:
      serviceAccount.main.staticToken: false
    asserts:
      - documentSelector:
          path: $[?(@.kind == "ServiceAccount")].metadata.name
          value: release-name
        notExists:
          path: secrets
      - not: true
        containsDocument:
          apiVersion: v1
          kind: Secret
          name: release-name-main-sa-token
          any: true

  - it: serviceAccount can be created with a static token
    set:
      serviceAccount.main.staticToken: true
    asserts:
      - documentSelector:
          path: $[?(@.kind == "ServiceAccount")].metadata.name
          value: release-name
        equal:
          path: secrets
          value:
            - name: release-name-main-sa-token
      - containsDocument:
          apiVersion: v1
          kind: Secret
          name: release-name-main-sa-token
          any: true
