---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: networkPolicy - fields - podSelector
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: networkpolicy targets the correct controller by default
    set:
      networkpolicies:
        main:
          controller: main
          policyTypes:
            - Ingress
            - Egress
          rules: {}
    documentSelector:
      path: $[?(@.kind == "NetworkPolicy")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.podSelector
          value:
            matchLabels:
              app.kubernetes.io/controller: main
              app.kubernetes.io/instance: RELEASE-NAME
              app.kubernetes.io/name: RELEASE-NAME

  - it: networkpolicy targets supports custom podSelector
    set:
      networkpolicies:
        main:
          controller: main
          policyTypes:
            - Ingress
            - Egress
          podSelector: {}
          rules: {}
    documentSelector:
      path: $[?(@.kind == "NetworkPolicy")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.podSelector
          value: {}
