---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: "networkPolicy - metadata - annotations"
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  networkpolicies.main:
    controller: main
    policyTypes:
      - Ingress
      - Egress
    rules: {}
tests:
  - it: no annotations are set by default
    documentSelector:
      path: $[?(@.kind == "NetworkPolicy")].metadata.name
      value: release-name
    asserts:
      - notExists:
          path: metadata.annotations

  - it: custom annotations
    set:
      networkpolicies.main.annotations:
        test_annotation: test
    documentSelector:
      path: $[?(@.kind == "NetworkPolicy")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: metadata.annotations
          value:
            test_annotation: test

  - it: custom annotations mixed with global annotations
    set:
      global.annotations:
        global_annotation: test
      networkpolicies.main.annotations:
        test_annotation: test
    documentSelector:
      path: $[?(@.kind == "NetworkPolicy")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: metadata.annotations
          value:
            global_annotation: test
            test_annotation: test
