---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: serviceMonitor - field - targetLabels
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: targetLabels can be configured
    set:
      serviceMonitor:
        main:
          serviceName: "{{ .Release.Name }}"
          endpoints:
            - port: http
              scheme: http
              path: /metrics
              interval: 1m
              scrapeTimeout: 10s
          targetLabels:
            - testlabel1
            - testlabel2
    documentSelector:
      path: $[?(@.kind == "ServiceMonitor")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.targetLabels
          value:
            - testlabel1
            - testlabel2
