---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: serviceMonitor - presence
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: a serviceMonitor is not created by default
    asserts:
      - not: true
        containsDocument:
          kind: ServiceMonitor
          apiVersion: monitoring.coreos.com/v1
          name: RELEASE-NAME
          any: true

  - it: a serviceMonitor is not created when disabled
    set:
      serviceMonitor:
        main:
          enabled: false
          serviceName: test
    asserts:
      - not: true
        containsDocument:
          kind: ServiceMonitor
          apiVersion: monitoring.coreos.com/v1
          name: RELEASE-NAME
          any: true
