---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: daemonset - metadata - annotations
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  controllers.main:
    type: daemonset
tests:
  - it: no annotations are set by default
    documentSelector:
      path: $[?(@.kind == "DaemonSet")].metadata.name
      value: release-name
    asserts:
      - notExists:
          path: metadata.annotations

  - it: custom annotations
    set:
      controllers.main.annotations:
        test_annotation: test
    documentSelector:
      path: $[?(@.kind == "DaemonSet")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: metadata.annotations
          value:
            test_annotation: test

  - it: custom annotations mixed with global annotations
    set:
      global.annotations:
        global_annotation: test
      controllers.main.annotations:
        test_annotation: test
    documentSelector:
      path: $[?(@.kind == "DaemonSet")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: metadata.annotations
          value:
            global_annotation: test
            test_annotation: test
