---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: pod - fields - imagePullSecrets
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default should pass
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - notExists:
          path: spec.template.spec.imagePullSecrets

  - it: defaultPodOption should pass
    set:
      defaultPodOptions:
        imagePullSecrets:
          - name: my-pull-secret
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.imagePullSecrets
          value:
            - name: my-pull-secret

  - it: defaultPodOption with pod override should pass
    set:
      defaultPodOptions:
        imagePullSecrets:
          - name: my-pull-secret
      controllers:
        main:
          pod:
            imagePullSecrets:
              - name: my-other-secret
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.imagePullSecrets
          value:
            - name: my-other-secret
