---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: pod - fields - volumes (secret)
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  secrets:
    mySettings:
      stringData:
        test: testvalue
  persistence:
    secret:
      type: secret
tests:
  - it: secret persistence type should pass
    set:
      persistence:
        secret:
          name: mySettings
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.volumes[0]
          value:
            name: secret
            secret:
              secretName: mySettings

  - it: secret persistence type with name template should pass
    set:
      persistence:
        secret:
          name: "{{ .Release.Name | lower }}-config"
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.volumes[0]
          value:
            name: secret
            secret:
              secretName: release-name-config

  - it: secret persistence type with identifier reference should pass
    set:
      persistence:
        secret:
          identifier: mySettings
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.volumes[0]
          value:
            name: secret
            secret:
              secretName: release-name
