---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: pod - fields - containers - order
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: with default order
    set:
      controllers.main.containers:
        main:
          image:
            repository: test
            tag: test
        additional1:
          image:
            repository: test
            tag: test
        additional2:
          image:
            repository: test
            tag: test
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - lengthEqual:
          path: spec.template.spec.containers
          count: 3
      - equal:
          path: spec.template.spec.containers[0].name
          value: additional1
      - equal:
          path: spec.template.spec.containers[1].name
          value: additional2
      - equal:
          path: spec.template.spec.containers[2].name
          value: main

  - it: with dependsOn
    set:
      controllers.main.containers:
        additional1:
          dependsOn: additional3
          image:
            repository: test
            tag: test
        additional2:
          dependsOn: additional3
          image:
            repository: test
            tag: test
        additional3:
          dependsOn: main
          image:
            repository: test
            tag: test
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - lengthEqual:
          path: spec.template.spec.containers
          count: 4
      - equal:
          path: spec.template.spec.containers[0].name
          value: main
      - equal:
          path: spec.template.spec.containers[1].name
          value: additional3
      - equal:
          path: spec.template.spec.containers[2].name
          value: additional1
      - equal:
          path: spec.template.spec.containers[3].name
          value: additional2
