---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: pod - fields - containers - multiple
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: with explicit name should pass
    set:
      controllers.main.containers:
        additional1:
          nameOverride: template-test
          dependsOn: main
          image:
            repository: test
            tag: test
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[1].name
          value: template-test

  - it: with implicit name should pass
    set:
      controllers.main.containers:
        additional1:
          dependsOn: main
          image:
            repository: test
            tag: test
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[1].name
          value: additional1

  - it: with templated name should pass
    set:
      controllers.main.containers:
        additional1:
          nameOverride: "{{ .Release.Name | lower }}-container"
          dependsOn: main
          image:
            repository: test
            tag: test
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[1].name
          value: release-name-container

  - it: with custom env vars dict should pass
    set:
      controllers.main.containers:
        main:
          env:
            main_env: value
        additional1:
          dependsOn: main
          image:
            repository: test
            tag: test
          env:
            int: 1
            float: 1.5
            string: value_of_env
            template: "{{ .Release.Name | lower }}-admin"
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[0].env[0]
          value:
            name: main_env
            value: "value"
      - equal:
          path: spec.template.spec.containers[1].env[0]
          value:
            name: float
            value: "1.5"
      - equal:
          path: spec.template.spec.containers[1].env[1]
          value:
            name: int
            value: "1"
      - equal:
          path: spec.template.spec.containers[1].env[2]
          value:
            name: string
            value: value_of_env
      - equal:
          path: spec.template.spec.containers[1].env[3]
          value:
            name: template
            value: release-name-admin
