---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: controller - presence
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default should pass
    asserts:
      - containsDocument:
          apiVersion: apps/v1
          kind: Deployment
          name: release-name
          any: true

  - it: multiple controllers should pass
    set:
      controllers:
        second:
          containers:
            main:
              image:
                repository: ghcr.io/mendhak/http-https-echo
                tag: 31
    asserts:
      - containsDocument:
          apiVersion: apps/v1
          kind: Deployment
          name: release-name-main
          any: true
      - containsDocument:
          apiVersion: apps/v1
          kind: Deployment
          name: release-name-second
          any: true

  - it: disabled should pass
    set:
      controllers.main.enabled: false
    asserts:
      - not: true
        containsDocument:
          apiVersion: apps/v1
          kind: Deployment
          name: release-name
          any: true
