---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: controller types
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default should pass
    asserts:
      - documentIndex: &deploymentDoc 0
        matchRegex:
          path: kind
          pattern: "^(Deployment|Rollout)$"
      - documentIndex: *deploymentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME
      - documentIndex: *deploymentDoc
        equal:
          path: metadata.labels['app.kubernetes.io/component']
          value: main

  - it: additional controllers should pass
    set:
      controllers:
        second:
          containers:
            main:
              image:
                repository: ghcr.io/mendhak/http-https-echo
                tag: 31
    asserts:
      - hasDocuments:
          count: 2
      - documentIndex: &firstDeploymentDoc 0
        matchRegex:
          path: kind
          pattern: "^(Deployment|Rollout)$"
      - documentIndex: *firstDeploymentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME-main
      - documentIndex: *firstDeploymentDoc
        equal:
          path: metadata.labels['app.kubernetes.io/component']
          value: main
      - documentIndex: &secondDeploymentDoc 1
        matchRegex:
          path: kind
          pattern: "^(Deployment|Rollout)$"
      - documentIndex: *secondDeploymentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME-second
      - documentIndex: *secondDeploymentDoc
        equal:
          path: metadata.labels['app.kubernetes.io/component']
          value: second

  - it: additional controllers with nameOverride should pass
    set:
      controllers:
        main:
          nameOverride: "{{ .Release.Name }}"
        second:
          nameOverride: testOverride
          containers:
            main:
              image:
                repository: ghcr.io/mendhak/http-https-echo
                tag: 31
    asserts:
      - hasDocuments:
          count: 2
      - documentIndex: &firstDeploymentDoc 0
        matchRegex:
          path: kind
          pattern: "^(Deployment|Rollout)$"
      - documentIndex: *firstDeploymentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME
      - documentIndex: *firstDeploymentDoc
        equal:
          path: metadata.labels['app.kubernetes.io/component']
          value: main
      - documentIndex: &secondDeploymentDoc 1
        matchRegex:
          path: kind
          pattern: "^(Deployment|Rollout)$"
      - documentIndex: *secondDeploymentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME-testOverride
      - documentIndex: *secondDeploymentDoc
        equal:
          path: metadata.labels['app.kubernetes.io/component']
          value: second

  - it: rollout should pass
    set:
      controllers.main.type: rollout
    asserts:
      - documentIndex: &ControllerDoc 0
        isKind:
          of: Rollout
      - documentIndex: *ControllerDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME

  - it: daemonset should pass
    set:
      controllers.main.type: daemonset
    asserts:
      - documentIndex: &ControllerDoc 0
        isKind:
          of: DaemonSet
      - documentIndex: *ControllerDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME

  - it: statefulset should pass
    set:
      controllers.main.type: statefulset
    asserts:
      - documentIndex: &ControllerDoc 0
        isKind:
          of: StatefulSet
      - documentIndex: *ControllerDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME

  - it: cronjob should pass
    set:
      controllers.main.type: cronjob
      controllers.main.cronjob.schedule: "*/20 * * * *"
    asserts:
      - documentIndex: &ControllerDoc 0
        isKind:
          of: CronJob
      - documentIndex: *ControllerDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME

  - it: disabled should pass
    set:
      controllers.main.enabled: false
    asserts:
      - hasDocuments:
          count: 0
