annotations:
  artifacthub.io/changes: "- kind: fixed\n  description: |-\n    Fixed name suffix\
    \ for HTTPRoute\n- kind: fixed\n  description: |-\n    Fixed incorrect default\
    \ backendRefs values in HTTPRoute"
apiVersion: v2
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 3.7.3
description: A common powered chart template. This can be useful for small projects
  that don't have their own chart.
kubeVersion: '>=1.22.0-0'
maintainers:
- email: me@bjw-s.dev
  name: bjw-s
name: app-template
sources:
- https://github.com/bjw-s-labs/helm-charts
version: 3.7.4
