---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: route - fields - rules - matches
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: path matches should only be used for HTTPRoutes and GRPCRoutes
    set:
      route:
        main:
          kind: HTTPRoute
          parentRefs:
            - name: parentName
              namespace: parentNamespace
          rules:
            - backendRefs:
                - name: test
                  namespace: test
                  kind: Service
                  weight: 1
              matches:
                - path:
                    type: PathPrefix
                    value: /test
        grpc:
          kind: GRPCRoute
          parentRefs:
            - name: parentName
              namespace: parentNamespace
          rules:
            - backendRefs:
                - name: test
                  namespace: test
                  kind: Service
                  weight: 1
              matches:
                - path:
                    type: PathPrefix
                    value: /test
        tcp:
          kind: TCPRoute
          parentRefs:
            - name: parentName
              namespace: parentNamespace
          rules:
            - backendRefs:
                - name: test
                  namespace: test
                  kind: Service
                  weight: 1
              matches:
                - path:
                    type: PathPrefix
                    value: /test
        tls:
          kind: TLSRoute
          parentRefs:
            - name: parentName
              namespace: parentNamespace
          rules:
            - backendRefs:
                - name: test
                  namespace: test
                  kind: Service
                  weight: 1
              matches:
                - path:
                    type: PathPrefix
                    value: /test
        udp:
          kind: UDPRoute
          parentRefs:
            - name: parentName
              namespace: parentNamespace
          rules:
            - backendRefs:
                - name: test
                  namespace: test
                  kind: Service
                  weight: 1
              matches:
                - path:
                    type: PathPrefix
                    value: /test
    asserts:
      - documentSelector:
          path: $[?(@.kind == "GRPCRoute")].metadata.name
          value: release-name-grpc
        equal:
          path: spec.rules[0].matches
          value:
            - path:
                type: PathPrefix
                value: /test
      - documentSelector:
          path: $[?(@.kind == "HTTPRoute")].metadata.name
          value: release-name-main
        equal:
          path: spec.rules[0].matches
          value:
            - path:
                type: PathPrefix
                value: /test
      - documentSelector:
          path: $[?(@.kind == "TCPRoute")].metadata.name
          value: release-name-tcp
        notExists:
          path: spec.rules[0].matches
      - documentSelector:
          path: $[?(@.kind == "TLSRoute")].metadata.name
          value: release-name-tls
        notExists:
          path: spec.rules[0].matches
      - documentSelector:
          path: $[?(@.kind == "UDPRoute")].metadata.name
          value: release-name-udp
        notExists:
          path: spec.rules[0].matches
