---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: route - presence
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: an HTTPRoute is not created by default
    asserts:
      - not: true
        containsDocument:
          kind: HTTPRoute
          apiVersion: gateway.networking.k8s.io/v1alpha2
          name: release-name
          any: true

  - it: an HTTPRoute is not created when disabled
    set:
      route.main.enabled: false
    asserts:
      - not: true
        containsDocument:
          kind: HTTPRoute
          apiVersion: gateway.networking.k8s.io/v1alpha2
          name: release-name
          any: true

  - it: an HTTPRoute is created when explicitly enabled
    set:
      route.main:
        enabled: true
        parentRefs:
          - name: test
            namespace: test
    asserts:
      - containsDocument:
          kind: HTTPRoute
          apiVersion: gateway.networking.k8s.io/v1alpha2
          name: release-name
          any: true

  - it: multiple HTTPRoute are created when configured
    set:
      route:
        main:
          parentRefs:
            - name: main
              namespace: main
        test:
          parentRefs:
            - name: test
              namespace: test
    asserts:
      - containsDocument:
          kind: HTTPRoute
          apiVersion: gateway.networking.k8s.io/v1alpha2
          name: release-name-main
          any: true
      - containsDocument:
          kind: HTTPRoute
          apiVersion: gateway.networking.k8s.io/v1alpha2
          name: release-name-test
          any: true
