---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: rawResource - presence
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  rawResources:
    endpoint:
      apiVersion: v1
      kind: Endpoint
      spec:
        subsets:
          - addresses:
            - ip: 127.0.0.1
            ports:
            - name: "{{ .Release.Name }}"
              port: 443
              protocol: TCP
tests:
  - it: raw resources are enabled by default
    documentSelector:
      path: $[?(@.kind == "Endpoint")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: subsets[0].addresses[0].ip
          value: 127.0.0.1

  - it: raw resources can be disabled
    set:
      rawResources.endpoint.enabled: false
    asserts:
      - not: true
        containsDocument:
          kind: Endpoint
          apiVersion: v1
          any: true

  - it: spec can render Helm template
    set:
      rawResources.endpoint:
        spec:
          subsets:
            - addresses:
              - ip: 127.0.0.1
              ports:
              - name: "{{ .Release.Name }}"
                port: 443
                protocol: TCP
    documentSelector:
      path: $[?(@.kind == "Endpoint")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: subsets[0].ports[0].name
          value: RELEASE-NAME
