---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: pvc - metadata - annotations
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  persistence.test:
    type: persistentVolumeClaim
    suffix: test
    accessMode: ReadWriteOnce
    size: 1Gi
tests:
  - it: no annotations are set by default
    documentSelector:
      path: $[?(@.kind == "PersistentVolumeClaim")].metadata.name
      value: release-name-test
    asserts:
      - notExists:
          path: metadata.annotations

  - it: custom annotations
    set:
      persistence.test.annotations:
        test_annotation: test
    documentSelector:
      path: $[?(@.kind == "PersistentVolumeClaim")].metadata.name
      value: release-name-test
    asserts:
      - equal:
          path: metadata.annotations
          value:
            test_annotation: test

  - it: custom annotations mixed with global annotations
    set:
      global.annotations:
        global_annotation: test
      persistence.test.annotations:
        test_annotation: test
    documentSelector:
      path: $[?(@.kind == "PersistentVolumeClaim")].metadata.name
      value: release-name-test
    asserts:
      - equal:
          path: metadata.annotations
          value:
            global_annotation: test
            test_annotation: test
