---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: pvc - metadata - labels
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  persistence.test:
    type: persistentVolumeClaim
    suffix: test
    accessMode: ReadWriteOnce
    size: 1Gi
tests:
  - it: default labels
    documentSelector:
      path: $[?(@.kind == "PersistentVolumeClaim")].metadata.name
      value: release-name-test
    asserts:
      - equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0

  - it: custom labels
    set:
      persistence.test.labels:
        test_label: test
    documentSelector:
      path: $[?(@.kind == "PersistentVolumeClaim")].metadata.name
      value: release-name-test
    asserts:
      - equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0
            test_label: test

  - it: custom labels mixed with global labels
    set:
      global.labels:
        global_label: test
      persistence.test.labels:
        test_label: test
    documentSelector:
      path: $[?(@.kind == "PersistentVolumeClaim")].metadata.name
      value: release-name-test
    asserts:
      - equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            global_label: test
            helm.sh/chart: common-test-1.0.0
            test_label: test
