---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: nameOverride tests
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default name is set to release name
    asserts:
      - documentIndex: &ControllerDoc 0
        matchRegex:
          path: kind
          pattern: "^(Deployment|Rollout)$"
      - documentIndex: *ControllerDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME

  - it: global.nameOverride can be set
    set:
      global.nameOverride: custom-name
    asserts:
      - documentIndex: &ControllerDoc 0
        matchRegex:
          path: kind
          pattern: "^(Deployment|Rollout)$"
      - documentIndex: *ControllerDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME-custom-name
