---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: job - fields - parallelism
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  controllers.main.type: job
tests:
  - it: default configuration should pass
    documentSelector:
      path: $[?(@.kind == "Job")].metadata.name
      value: release-name
    asserts:
      - notExists:
          path: spec.parallelism

  - it: custom configuration should pass
    set:
      controllers.main.job.parallelism: 3
    documentSelector:
      path: $[?(@.kind == "Job")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.parallelism
          value: 3
