---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: persistence claimnames
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default should pass
    set:
      persistence:
        config:
          accessMode: ReadWriteOnce
          size: 1Gi
    asserts:
      - documentIndex: 1
        matchRegex:
          path: kind
          pattern: "^(Deployment|Rollout)$"
      - documentIndex: 1
        equal:
          path: spec.template.spec.volumes[0]
          value:
            name: config
            persistentVolumeClaim:
              claimName: RELEASE-NAME-config

  - it: with existingClaim should pass
    set:
      persistence:
        existingClaim:
          existingClaim: myClaim
    asserts:
      - documentIndex: 0
        matchRegex:
          path: kind
          pattern: "^(Deployment|Rollout)$"
      - documentIndex: 0
        equal:
          path: spec.template.spec.volumes[0]
          value:
            name: existingClaim
            persistentVolumeClaim:
              claimName: myClaim

  - it: disabled suffix should pass
    set:
      persistence:
        claimWithoutSuffix:
          nameOverride: "-"
          accessMode: ReadWriteMany
          size: 1G
    asserts:
      - documentIndex: 1
        matchRegex:
          path: kind
          pattern: "^(Deployment|Rollout)$"
      - documentIndex: 1
        equal:
          path: spec.template.spec.volumes[0]
          value:
            name: claimWithoutSuffix
            persistentVolumeClaim:
              claimName: RELEASE-NAME

  - it: custom suffix should pass
    set:
      persistence:
        claimWithNameOverride:
          nameOverride: suffix
          accessMode: ReadWriteMany
          size: 1G
    asserts:
      - documentIndex: 1
        matchRegex:
          path: kind
          pattern: "^(Deployment|Rollout)$"
      - documentIndex: 1
        equal:
          path: spec.template.spec.volumes[0]
          value:
            name: claimWithNameOverride
            persistentVolumeClaim:
              claimName: RELEASE-NAME-suffix
