---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: container - fields - command
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default should pass
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - notExists:
          path: spec.template.spec.containers[0].command

  - it: single string should pass
    set:
      controllers.main.containers.main.command: /bin/sh
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[0].command
          value:
            - /bin/sh

  - it: multiline string should pass
    set:
      controllers.main.containers.main.command: |
        /bin/sh
        -c
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[0].command
          value:
            - |-
              /bin/sh
              -c

  - it: single quoted string should pass
    set:
      controllers.main.containers.main.command: "/bin/sh"
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[0].command
          value:
            - /bin/sh

  - it: list of strings should pass
    set:
      controllers.main.containers.main.command:
        - /bin/sh
        - "-c"
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[0].command
          value:
            - /bin/sh
            - -c

  - it: command from defaultContainerOptions should pass
    set:
      controllers.main.defaultContainerOptions:
        command: value_of_command
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[0].command
          value:
            - value_of_command

  - it: command from defaultContainerOptions with container override should pass
    set:
      controllers.main.defaultContainerOptions:
        command: value_of_command
      controllers.main.containers.main.command:
        - value 1
        - value 2
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[0].command
          value:
            - value 1
            - value 2
