---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: container - fields - image
templates:
  - common.yaml
tests:
  - it: string tag should pass
    values:
      - ../_values/controllers_main_default_container.yaml
    set:
      controllers.main.containers.main.image:
        repository: ghcr.io/mendhak/http-https-echo
        tag: latest
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: ghcr.io/mendhak/http-https-echo:latest

  - it: integer tag should pass
    values:
      - ../_values/controllers_main_default_container.yaml
    set:
      controllers.main.containers.main.image:
        repository: ghcr.io/mendhak/http-https-echo
        tag: 1.23
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: ghcr.io/mendhak/http-https-echo:1.23

  - it: template tag should pass
    values:
      - ../_values/controllers_main_default_container.yaml
    set:
      controllers.main.containers.main.image:
        repository: ghcr.io/mendhak/http-https-echo
        tag: "{{.Chart.Version}}"
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: ghcr.io/mendhak/http-https-echo:1.0.0

  - it: tag from defaultContainerOptions should pass
    set:
      controllers.main:
        defaultContainerOptions:
          image:
            repository: ghcr.io/mendhak/http-https-echo
            tag: 32
        containers:
          main: {} # needed to have at least a container enabled
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: ghcr.io/mendhak/http-https-echo:32

  - it: tag from defaultContainerOptions with container override should pass
    set:
      controllers.main.defaultContainerOptions.image:
        repository: ghcr.io/mendhak/http-https-echo
        tag: 32
      controllers.main.containers.main.image:
        repository: ghcr.io/mendhak/http-https-echo-override
        tag: 33
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: ghcr.io/mendhak/http-https-echo-override:33
