---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: cronjob - jobTemplate - metadata - annotations
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  controllers.main:
    type: cronjob
    cronjob:
      schedule: "*/20 * * * *"
tests:
  - it: jobTemplate metadata should pass
    set:
      controllers.main.pod.annotations:
        test_annotation: test
    documentSelector:
      path: $[?(@.kind == "CronJob")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.jobTemplate.spec.template.metadata.annotations
          value:
            test_annotation: test
