---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: secret - presence
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: secret is not present by default
    asserts:
      - not: true
        containsDocument:
          apiVersion: v1
          kind: Secret
          any: true

  - it: secrets are enabled by default
    set:
      secrets:
        secret:
          stringData:
            test: test
    asserts:
      - containsDocument:
          apiVersion: v1
          kind: Secret
          any: true
          name: release-name

  - it: secret is not present when disabled
    set:
      secrets:
        secret:
          enabled: false
          stringData:
            test: test
    asserts:
      - not: true
        containsDocument:
          apiVersion: v1
          kind: Secret
          any: true
          name: release-name

  - it: multiple secrets can be enabled
    set:
      secrets:
        secret:
          stringData:
            foo: bar
        secondary:
          stringData:
            test: test
    asserts:
      - containsDocument:
          apiVersion: v1
          kind: Secret
          any: true
          name: release-name-secret
      - containsDocument:
          apiVersion: v1
          kind: Secret
          any: true
          name: release-name-secondary
