---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: service - fields - externalName
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
  - ../_values/service_main_default.yaml
tests:
  - it: externalName can be configured for ExternalName service
    set:
      service:
        main:
          type: ExternalName
          externalName: my.database.example.com
    documentSelector:
      path: $[?(@.kind == "Service")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.externalName
          value: my.database.example.com
