---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: service - fields - ports
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
  - ../_values/service_main_default.yaml
tests:
  - it: ports are enabled by default
    documentSelector:
      path: $[?(@.kind == "Service")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.ports[0]
          value:
            name: http
            port: 8081
            protocol: TCP
            targetPort: 8081

  - it: multiple ports can be configured
    set:
      service:
        main:
          ports:
            http:
              enabled: false
            server:
              enabled: true
              port: 8080
            secondary:
              enabled: true
              port: 8081
    documentSelector:
      path: $[?(@.kind == "Service")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.ports[0]
          value:
            name: secondary
            port: 8081
            protocol: TCP
            targetPort: 8081
      - equal:
          path: spec.ports[1]
          value:
            name: server
            port: 8080
            protocol: TCP
            targetPort: 8080
