---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: configmap - metadata - labels
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default labels
    set:
      configMaps:
        config:
          data:
            test: test
    documentSelector:
      path: $[?(@.kind == "ConfigMap")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0

  - it: custom labels
    set:
      configMaps:
        config:
          data:
            test: test
          labels:
            test_label: test
    documentSelector:
      path: $[?(@.kind == "ConfigMap")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0
            test_label: test

  - it: custom labels mixed with global labels
    set:
      global.labels:
        global_label: test
      configMaps:
        config:
          data:
            test: test
          labels:
            test_label: test
    documentSelector:
      path: $[?(@.kind == "ConfigMap")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            global_label: test
            helm.sh/chart: common-test-1.0.0
            test_label: test

  - it: default metadata from folder should pass
    set:
      configMaps:
        config:
          data:
            test: test
      configMapsFromFolder:
        enabled: true
        basePath: ci/configMapsFolder
        configMapsOverrides:
          test_2:
            fileAttributeOverrides:
              helm.jpg:
                binary: true
              test_2.yaml:
                escaped: true
    asserts:
      - documentSelector:
          path: $[?(@.kind == "ConfigMap")].metadata.name
          value: release-name-config
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0
      - documentSelector:
          path: $[?(@.kind == "ConfigMap")].metadata.name
          value: release-name-test_1
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0
      - documentSelector:
          path: $[?(@.kind == "ConfigMap")].metadata.name
          value: release-name-test_2
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0

  - it: custom metadata from folder should pass
    set:
      configMaps:
        config:
          data:
            test: test
      configMapsFromFolder:
        enabled: true
        basePath: ci/configMapsFolder
        configMapsOverrides:
          test_2:
            labels:
              test: test_label
            fileAttributeOverrides:
              helm.jpg:
                binary: true
              test_2.yaml:
                escaped: true
    asserts:
      - documentSelector:
          path: $[?(@.kind == "ConfigMap")].metadata.name
          value: release-name-config
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0
      - documentSelector:
          path: $[?(@.kind == "ConfigMap")].metadata.name
          value: release-name-test_1
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0
      - documentSelector:
          path: $[?(@.kind == "ConfigMap")].metadata.name
          value: release-name-test_2
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            helm.sh/chart: common-test-1.0.0
            test: test_label
